name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        crate: ["orphan-instance-lang", "typelist"]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build ${{ matrix.crate }}
      run: cargo build --verbose -p ${{ matrix.crate }}
    - name: Test ${{ matrix.crate }}
      run: cargo test --verbose -p ${{ matrix.crate }}

